export type PlaceKind = 'city' | 'district' | 'street' | 'settlement' | 'region';

export type GazetteerPlace = {
  code: string;
  name: string;
  aliases: string[];
  lat: number;
  lon: number;
  kind: PlaceKind;
};

export const KHARKIV_CENTER = { lat: 49.9935, lon: 36.2304 };

export const GAZETTEER: GazetteerPlace[] = [
  {
    code: 'kharkiv',
    name: 'Харків',
    aliases: ['харків', 'харьков', 'kharkiv', 'kharkov', 'харкову', 'харкова', 'харкові', 'по харкову', 'м. харків'],
    lat: KHARKIV_CENTER.lat,
    lon: KHARKIV_CENTER.lon,
    kind: 'city',
  },

  { code: 'center', name: 'Центр', aliases: ['центр', 'центр міста', 'центр города', 'нагірна', 'нагорный', 'центральний'], lat: 49.9935, lon: 36.2304, kind: 'district' },
  { code: 'levada', name: 'Левада', aliases: ['левада', 'леваду'], lat: 49.981, lon: 36.259, kind: 'district' },
  { code: 'moskalivka', name: 'Москалівка', aliases: ['москалівка', 'москалевка', 'москалівку', 'москалевку'], lat: 49.983, lon: 36.218, kind: 'district' },
  { code: 'derevianky', name: "Дерев'янки", aliases: ["дерев'янки", 'деревянки', "дерев'янка", 'деревянка'], lat: 50.035, lon: 36.268, kind: 'district' },
  { code: 'naukova', name: 'Наукова', aliases: ['наукова', 'научная', 'ст. наукова', 'станція наукова', 'метро наукова', 'район наукової'], lat: 50.0167, lon: 36.2247, kind: 'district' },
  { code: 'saltivka', name: 'Салтівка', aliases: ['салтівка', 'салтовка', 'східна салтівка'], lat: 50.024, lon: 36.336, kind: 'district' },
  {
    code: 'north_saltivka',
    name: 'Північна Салтівка',
    aliases: [
      'північна салтівка',
      'северная салтовка',
      'півн. салтівка',
      'сев. салтовка',
      'сс',
      'с.с',
      'с/с',
      'с с',
    ],
    lat: 50.043,
    lon: 36.355,
    kind: 'district',
  },
  { code: 'velyka_danylivka', name: 'Велика Данилівка', aliases: ['велика данилівка', 'большая даниловка', 'данилівка', 'даниловка', 'бд'], lat: 50.038, lon: 36.305, kind: 'district' },
  { code: 'pitomnyk', name: 'Питомник', aliases: ['питомник', 'пітомник'], lat: 50.074, lon: 36.318, kind: 'settlement' },
  { code: 'lisne', name: 'Лісне', aliases: ['лісне', 'лесное', 'лісне'], lat: 50.141, lon: 36.317, kind: 'settlement' },
  { code: 'zhuky', name: 'Жуки', aliases: ['жуки'], lat: 50.09, lon: 36.275, kind: 'settlement' },
  { code: 'oleksiivka', name: 'Олексіївка', aliases: ['олексіївка', 'алексеевка'], lat: 50.046, lon: 36.188, kind: 'district' },
  { code: 'pavlove_pole', name: 'Павлове Поле', aliases: ['павлове поле', 'павлово поле'], lat: 50.027, lon: 36.222, kind: 'district' },
  { code: 'pyatykhatky', name: "П'ятихатки", aliases: ['пятихатки', "п'ятихатки"], lat: 50.078, lon: 36.217, kind: 'district' },
  { code: 'kholodna_hora', name: 'Холодна Гора', aliases: ['холодна гора', 'холодная гора', 'холодногірський'], lat: 49.984, lon: 36.178, kind: 'district' },
  { code: 'nova_bavaria', name: 'Нова Баварія', aliases: ['нова баварія', 'новобаварський', 'новая бавария', 'залютине'], lat: 49.96, lon: 36.175, kind: 'district' },
  { code: 'osnova', name: 'Основа', aliases: ['основа', 'основянський'], lat: 49.958, lon: 36.235, kind: 'district' },
  { code: 'nemyshlia', name: 'Немишля', aliases: ['немишля', 'немишлянський', 'нові будинки', 'новые дома'], lat: 49.98, lon: 36.3, kind: 'district' },
  { code: 'htz', name: 'ХТЗ', aliases: ['хтз', 'індустріальний', 'индустриальный'], lat: 49.952, lon: 36.318, kind: 'district' },
  { code: 'rogan', name: 'Рогань', aliases: ['рогань'], lat: 49.94, lon: 36.36, kind: 'district' },
  { code: 'zhuravlivka', name: 'Журавлівка', aliases: ['журавлівка', 'журавлевка'], lat: 50.01, lon: 36.27, kind: 'district' },
  { code: 'kyivskyi', name: 'Київський район', aliases: ['київський район', 'киевский район', 'лісопарк'], lat: 50.02, lon: 36.25, kind: 'district' },
  { code: 'shevchenkivskyi', name: 'Шевченківський район', aliases: ['шевченківський', 'шевченковский', 'держпром', 'сокільники'], lat: 50.01, lon: 36.23, kind: 'district' },
  { code: 'slobidskyi', name: 'Слобідський район', aliases: ['слобідський', 'слободской'], lat: 49.97, lon: 36.27, kind: 'district' },
  { code: 'sortyrovka', name: 'Сортировка', aliases: ['сортировка', 'сортування'], lat: 49.99, lon: 36.16, kind: 'district' },
  { code: 'zhukhar', name: 'Жихарь', aliases: ['жихарь', 'жихар'], lat: 49.93, lon: 36.27, kind: 'district' },
  { code: 'barabashovo', name: 'Барабашово', aliases: ['барабашово', 'барабашова'], lat: 50.005, lon: 36.32, kind: 'district' },
  { code: 'selektsiine', name: 'Селекційне', aliases: ['селекційне', 'селекционное'], lat: 50.035, lon: 36.2, kind: 'district' },
  { code: 'shishkivka', name: 'Шишківка', aliases: ['шишківка', 'шишковка'], lat: 50.055, lon: 36.2, kind: 'district' },
  { code: 'lidiine', name: 'Лідне', aliases: ['лідне', 'лидное'], lat: 49.95, lon: 36.2, kind: 'district' },
  { code: 'novozhanove', name: 'Новожанове', aliases: ['новожанове', 'новожаново'], lat: 49.97, lon: 36.19, kind: 'district' },
  { code: 'pisochyn', name: 'Пісочин', aliases: ['пісочин', 'песочин'], lat: 49.96, lon: 36.12, kind: 'settlement' },
  { code: 'derhachi', name: 'Дергачі', aliases: ['дергачі', 'дергачи'], lat: 50.11, lon: 36.12, kind: 'settlement' },
  { code: 'chuhuiv', name: 'Чугуїв', aliases: ['чугуїв', 'чугуев'], lat: 49.835, lon: 36.686, kind: 'settlement' },
  {
    code: 'staryi_saltiv',
    name: 'Старий Салтів',
    aliases: [
      'старий салтів',
      'старый салтов',
      'старий салтов',
      'старый салтів',
      'ст салтов',
      'ст. салтов',
      'ст салтів',
      'ст. салтів',
      'стсалтов',
      'стсалтів',
    ],
    lat: 50.077,
    lon: 36.794,
    kind: 'settlement',
  },
  { code: 'merefa', name: 'Мерефа', aliases: ['мерефа'], lat: 49.82, lon: 36.05, kind: 'settlement' },

  { code: 'krasnopavlivka', name: 'Краснопавлівка', aliases: ['краснопавлівка', 'краснопавловка', 'краснопавлівку', 'краснопавловку'], lat: 49.137, lon: 36.323, kind: 'settlement' },
  { code: 'kehychivka', name: 'Кегичівка', aliases: ['кегичівка', 'кегичевка', 'кегичівку', 'кегичевку'], lat: 49.286, lon: 35.762, kind: 'settlement' },
  { code: 'lyptsi', name: 'Липці', aliases: ['липці', 'липцы'], lat: 50.156, lon: 36.379, kind: 'settlement' },
  { code: 'tsyrkuny', name: 'Циркуни', aliases: ['циркуни', 'цыркуны'], lat: 50.082, lon: 36.36, kind: 'settlement' },
  { code: 'ruska_lozova', name: 'Руська Лозова', aliases: ['руська лозова', 'русская лозовая'], lat: 50.138, lon: 36.281, kind: 'settlement' },
  { code: 'cherkaska_lozova', name: 'Черкаська Лозова', aliases: ['черкаська лозова', 'черкасская лозовая'], lat: 50.118, lon: 36.228, kind: 'settlement' },
  { code: 'slatyne', name: 'Слатине', aliases: ['слатине', 'слатино'], lat: 50.209, lon: 36.153, kind: 'settlement' },
  { code: 'barvinkove', name: 'Барвінкове', aliases: ['барвінкове', 'барвенково', 'барвінкове', 'барвенково'], lat: 48.907, lon: 36.996, kind: 'settlement' },
  { code: 'savyntsi', name: 'Савинці', aliases: ['савинці', 'савинцы', 'савинці', 'савинцы'], lat: 49.393, lon: 36.538, kind: 'settlement' },
  { code: 'blyzniuky', name: 'Близнюки', aliases: ['близнюки', 'близнюки'], lat: 48.857, lon: 36.555, kind: 'settlement' },
  { code: 'khotimlia', name: 'Хотімля', aliases: ['хотімля', 'хотимля'], lat: 50.161, lon: 36.722, kind: 'settlement' },
  { code: 'sakhnovshchyna', name: 'Сахновщина', aliases: ['сахновщина', 'сахновщину', 'сахновщине'], lat: 49.153, lon: 35.872, kind: 'settlement' },
  { code: 'kozacha_lopan', name: 'Козача Лопань', aliases: ['козача лопань', 'казачья лопань'], lat: 50.333, lon: 36.2, kind: 'settlement' },
  { code: 'vovchansk', name: 'Вовчанськ', aliases: ['вовчанськ', 'волчанск'], lat: 50.288, lon: 36.946, kind: 'settlement' },
  { code: 'kupyansk', name: "Куп'янськ", aliases: ["куп'янськ", 'купянск', 'купянськ'], lat: 49.71, lon: 37.617, kind: 'settlement' },
  { code: 'izium', name: 'Ізюм', aliases: ['ізюм', 'изюм'], lat: 49.213, lon: 37.257, kind: 'settlement' },
  { code: 'balakliia', name: 'Балаклія', aliases: ['балаклія', 'балаклея'], lat: 49.463, lon: 36.859, kind: 'settlement' },
  { code: 'lozova', name: 'Лозова', aliases: ['лозова', 'лозовая'], lat: 48.889, lon: 36.317, kind: 'settlement' },
  { code: 'krasnohrad', name: 'Красноград', aliases: ['красноград'], lat: 49.372, lon: 35.443, kind: 'settlement' },
  { code: 'zmiiv', name: 'Зміїв', aliases: ['зміїв', 'змеев', 'зміїв'], lat: 49.688, lon: 36.356, kind: 'settlement' },
  { code: 'pervomaiskyi', name: 'Первомайський', aliases: ['первомайський', 'первомайский'], lat: 49.387, lon: 36.214, kind: 'settlement' },
  { code: 'bohodukhiv', name: 'Богодухів', aliases: ['богодухів', 'богодухов'], lat: 50.161, lon: 35.527, kind: 'settlement' },
  { code: 'valky', name: 'Валки', aliases: ['валки'], lat: 49.838, lon: 35.618, kind: 'settlement' },
  { code: 'zolochiv', name: 'Золочів', aliases: ['золочів', 'золочев'], lat: 50.28, lon: 35.969, kind: 'settlement' },
  { code: 'oblast_north', name: 'Північ області', aliases: ['північ області', 'север области', 'північна частина області', 'северная часть области', 'північний пригород', 'северный пригород'], lat: 50.18, lon: 36.22, kind: 'region' },
  { code: 'oblast_south', name: 'Південь області', aliases: ['південь області', 'юг области', 'південна частина області', 'южная часть области'], lat: 49.4, lon: 36.25, kind: 'region' },
  { code: 'oblast_east', name: 'Схід області', aliases: ['схід області', 'восток области', 'східна частина області', 'восточная часть области'], lat: 49.9, lon: 37.25, kind: 'region' },
  { code: 'oblast_west', name: 'Захід області', aliases: ['захід області', 'запад области', 'західна частина області', 'западная часть области'], lat: 49.95, lon: 35.7, kind: 'region' },

  { code: 'st_sumska', name: 'вул. Сумська', aliases: ['сумська', 'сумская', 'вул. сумська', 'улица сумская'], lat: 50.004, lon: 36.234, kind: 'street' },
  { code: 'st_pushkinska', name: 'вул. Пушкінська', aliases: ['пушкінська', 'пушкинская', 'вул. пушкінська'], lat: 50.002, lon: 36.247, kind: 'street' },
  { code: 'st_nauky', name: 'просп. Науки', aliases: ['проспект науки', 'просп. науки', 'пр. науки', 'ленина проспект', 'вул. наукова'], lat: 50.015, lon: 36.226, kind: 'street' },
  {
    code: 'st_otamanovsky',
    name: 'вул. Отаманівського',
    aliases: [
      'отаманівського',
      'отамановського',
      'отамановского',
      'отманановского',
      'отаманівська',
      'отамановська',
      'отамана кальнишевського',
      'кальнишевського',
      'вул. отаманівського',
      'вул. отамановського',
    ],
    lat: 50.0102,
    lon: 36.2264,
    kind: 'street',
  },
  { code: 'st_heroyiv_kharkova', name: 'просп. Героїв Харкова', aliases: ['героїв харкова', 'героев харькова', 'московський проспект', 'московский проспект', 'пр. героїв харкова'], lat: 49.98, lon: 36.26, kind: 'street' },
  { code: 'st_gagarina', name: 'просп. Гагаріна', aliases: ['гагаріна', 'гагарина', 'проспект гагаріна', 'пр. гагаріна'], lat: 49.97, lon: 36.25, kind: 'street' },
  { code: 'st_traktorobud', name: 'просп. Тракторобудівників', aliases: ['тракторобудівників', 'тракторостроителей', 'пр. тракторобудівників'], lat: 49.955, lon: 36.33, kind: 'street' },
  { code: 'st_saltivske', name: 'Салтівське шосе', aliases: ['салтівське шосе', 'салтовское шоссе', 'салтівське'], lat: 50.03, lon: 36.32, kind: 'street' },
  { code: 'st_pavlova', name: 'вул. Академіка Павлова', aliases: ['академіка павлова', 'академика павлова', 'павлова'], lat: 50.02, lon: 36.34, kind: 'street' },
  { code: 'st_klochkivska', name: 'вул. Клочківська', aliases: ['клочківська', 'клочковская'], lat: 50.01, lon: 36.21, kind: 'street' },
  { code: 'st_poltavskyi', name: 'Полтавський Шлях', aliases: ['полтавський шлях', 'полтавский шлях', 'свердлова'], lat: 49.985, lon: 36.2, kind: 'street' },
  { code: 'st_heroiv_pratsi', name: 'вул. Героїв Праці', aliases: ['героїв праці', 'героев труда', 'вул. героїв праці'], lat: 50.03, lon: 36.345, kind: 'street' },
  { code: 'st_shevchenka', name: 'вул. Шевченка', aliases: ['шевченка', 'шевченко'], lat: 50.0, lon: 36.245, kind: 'street' },
  { code: 'st_svobody', name: 'майдан Свободи', aliases: ['майдан свободи', 'площадь свободы', 'держпром'], lat: 50.0046, lon: 36.231, kind: 'street' },
  { code: 'st_konstytutsii', name: 'майдан Конституції', aliases: ['майдан конституції', 'площадь конституции'], lat: 49.992, lon: 36.231, kind: 'street' },
  { code: 'st_landau', name: 'просп. Льва Ландау', aliases: ['ландау', 'льва ландау', '50-річчя срср', '50 лет ссср'], lat: 49.97, lon: 36.3, kind: 'street' },
  { code: 'st_oleksiivska', name: 'вул. Олексіївська', aliases: ['олексіївська', 'алексеевская'], lat: 50.04, lon: 36.19, kind: 'street' },
  { code: 'st_shironintsiv', name: 'вул. Гвардійців Широнінців', aliases: ['гвардійців широнінців', 'гвардейцев широнинцев', 'широнінців'], lat: 50.035, lon: 36.35, kind: 'street' },
  { code: 'st_valentynivska', name: 'вул. Валентинівська', aliases: ['валентинівська', 'валентиновская'], lat: 50.04, lon: 36.34, kind: 'street' },
  { code: 'st_serdiuka', name: 'вул. Леся Сердюка', aliases: ['леся сердюка', 'сердюка'], lat: 50.038, lon: 36.36, kind: 'street' },
  { code: 'st_novhorodska', name: 'вул. Новгородська', aliases: ['новгородська', 'новгородская'], lat: 50.028, lon: 36.33, kind: 'street' },
  { code: 'st_druzhby', name: 'вул. Дружби Народів', aliases: ['дружби народів', 'дружбы народов'], lat: 50.025, lon: 36.35, kind: 'street' },
  { code: 'st_neskorenykh', name: 'просп. Нескорених', aliases: ['нескорених', 'героїв сталінграда', 'героев сталинграда'], lat: 50.04, lon: 36.21, kind: 'street' },
  { code: 'st_peremohy', name: 'просп. Перемоги', aliases: ['перемоги', 'победы', 'проспект перемоги'], lat: 50.03, lon: 36.2, kind: 'street' },
  { code: 'st_rymarska', name: 'вул. Римарська', aliases: ['римарська', 'рымарская'], lat: 49.995, lon: 36.23, kind: 'street' },
  { code: 'st_myronosytska', name: 'вул. Мироносицька', aliases: ['мироносицька', 'мироносицкая'], lat: 50.0, lon: 36.24, kind: 'street' },
  { code: 'st_chernyshevska', name: 'вул. Чернишевська', aliases: ['чернишевська', 'чернышевская'], lat: 49.998, lon: 36.25, kind: 'street' },
  { code: 'st_darvina', name: 'вул. Дарвіна', aliases: ['дарвіна', 'дарвина'], lat: 50.001, lon: 36.242, kind: 'street' },
  { code: 'st_kholodnohirska', name: 'вул. Холодногірська', aliases: ['холодногірська', 'холодногорская'], lat: 49.986, lon: 36.185, kind: 'street' },
  { code: 'st_airport', name: 'аеропорт', aliases: ['аеропорт', 'аэропорт', 'основинський аеропорт'], lat: 49.925, lon: 36.29, kind: 'street' },
];
